# Generated by Django 6.0 on 2025-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingcity",
            name="main_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingservice",
            name="main_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingservicecity",
            name="main_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingservicecityimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketingserviceimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
