# Generated by Django 6.0 on 2025-12-27 15:24

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0002_marketingcity_main_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingcity",
            name="main_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL or /root-relative path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingservice",
            name="main_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL or /root-relative path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingservicecity",
            name="main_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL or /root-relative path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingservicecityimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="marketing/service_city/gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="marketingservicecityimage",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL or /root-relative path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingserviceimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="marketing/services/gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="marketingserviceimage",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL or /root-relative path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
    ]
