# Generated by Django 6.0 on 2025-12-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_provider_works_in_salon_only"),
        ("interface", "0003_alter_marketingcity_main_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_phone", models.CharField(max_length=64)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marketing_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="interface.marketingservice",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="booking.zone",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="MarketingCity",
        ),
        migrations.DeleteModel(
            name="MarketingDistrict",
        ),
        migrations.DeleteModel(
            name="MarketingServiceCity",
        ),
        migrations.DeleteModel(
            name="MarketingServiceCityImage",
        ),
    ]
