# Generated by Django 6.0 on 2025-12-28 23:08

import django.db.models.deletion
import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_provider_works_in_salon_only"),
        ("interface", "0004_remove_marketingservicecity_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                ("highlights", models.JSONField(blank=True, default=list)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketing/zones/main/"
                    ),
                ),
                (
                    "hero_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Upload an image or provide an absolute URL or /root-relative path.",
                        max_length=500,
                        validators=[
                            interface.validators.validate_absolute_or_root_relative_url
                        ],
                    ),
                ),
                ("meta_description", models.TextField(blank=True)),
                (
                    "zone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_profile",
                        to="booking.zone",
                    ),
                ),
            ],
            options={
                "ordering": ("zone__name",),
            },
        ),
    ]
