# Generated by Django 6.0 on 2025-12-29 18:10

import django.utils.timezone
import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0005_marketingzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="desired_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marketingservice",
            name="main_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingserviceimage",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketingzone",
            name="hero_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
    ]
