# Generated by Django 6.0 on 2026-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0006_servicerequest_desired_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="location_preference",
            field=models.CharField(
                choices=[
                    ("client_home", "À domicile"),
                    ("salon", "En salon / chez le prestataire"),
                ],
                default="client_home",
                max_length=32,
            ),
        ),
    ]
