# Generated by Django 6.0.1 on 2026-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0008_rename_servicerequest_client_phone_to_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="client_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="client_email",
            field=models.EmailField(max_length=254),
        ),
    ]
