# Generated by Django 6.0.2 on 2026-02-13 15:16

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0010_marketingservicezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=120)),
                ("review_text", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketing/reviews/"
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[
                            interface.validators.validate_absolute_or_root_relative_url
                        ],
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="hair_length",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="inspiration_picture_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="meche_provided",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="location_preference",
            field=models.CharField(
                choices=[
                    ("client_home", "À domicile"),
                    ("salon", "En salon / chez la prestataire ou le prestataire"),
                ],
                default="client_home",
                max_length=32,
            ),
        ),
    ]
