# Generated by Django 6.0.2 on 2026-02-13 16:03

from django.db import migrations, models


def move_inspiration_url_to_list(apps, schema_editor):
    ServiceRequest = apps.get_model("interface", "ServiceRequest")
    for request in ServiceRequest.objects.all().only("id", "inspiration_picture_url"):
        if request.inspiration_picture_url:
            request.inspiration_picture_urls = [request.inspiration_picture_url]
            request.save(update_fields=["inspiration_picture_urls"])


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0011_clientreview_servicerequest_hair_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="inspiration_picture_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(move_inspiration_url_to_list, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="servicerequest",
            name="inspiration_picture_url",
        ),
    ]
