# Generated by Django 6.0.2 on 2026-02-14 16:25

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0012_remove_servicerequest_inspiration_picture_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientreview",
            name="media_kind",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="clientreview",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="marketing/reviews/videos/"
            ),
        ),
        migrations.AddField(
            model_name="clientreview",
            name="video_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
    ]
