# Generated by Django 6.0.2 on 2026-02-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0013_clientreview_media_kind_clientreview_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingservice",
            name="long_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="marketingservice",
            name="long_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="marketingservice",
            name="short_intro",
            field=models.TextField(blank=True),
        ),
    ]
