# Generated by Django 6.0.2 on 2026-02-24 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0025_provider_deposit_percentage"),
        ("interface", "0016_providerbookingdraft"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickCheckoutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("desired_date", models.DateTimeField()),
                ("hair_length", models.CharField(max_length=120)),
                (
                    "location_preference",
                    models.CharField(
                        choices=[
                            ("domicile", "À domicile"),
                            (
                                "salon",
                                "En salon / chez la prestataire ou le prestataire",
                            ),
                        ],
                        default="domicile",
                        max_length=32,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("client_address", models.TextField(blank=True)),
                ("general_adjustment", models.CharField(blank=True, max_length=120)),
                ("meche", models.BooleanField(default=False)),
                ("free_text", models.TextField(blank=True)),
                (
                    "fixed_price_cents",
                    models.PositiveIntegerField(
                        help_text="Prix fixé pour ce checkout (en centimes)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_checkout_pages",
                        to="booking.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_checkout_pages",
                        to="booking.service",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
