# Generated by Django 6.0.2 on 2026-02-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0017_quickcheckoutpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quickcheckoutpage",
            name="token",
        ),
    ]
