# Generated by Django 6.0.3 on 2026-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0019_quickcheckoutpage_simplify_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="availabilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="client_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="salon_area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
