# Generated by Django 6.0.3 on 2026-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0020_servicerequest_availabilities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="client_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="desired_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="location_preference",
            field=models.CharField(
                choices=[
                    ("client_home", "À domicile"),
                    ("salon", "Chez la prestataire / le prestataire"),
                ],
                default="client_home",
                max_length=32,
            ),
        ),
    ]
