# Generated by Django 6.0.3 on 2026-03-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0021_alter_servicerequest_client_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("provider_question", "Question prestataire"),
                            ("quick_request", "Demande rapide"),
                            ("provider_appointment_request", "Demande RDV prestataire"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("in_progress", "En cours"),
                            ("waiting_client", "En attente client"),
                            ("waiting_provider", "En attente prestataire"),
                            ("done", "Traité"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("source_label", models.CharField(blank=True, max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="interface.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
