# Generated by Django 6.0.3 on 2026-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0022_interaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouveau"),
                    ("in_progress", "En cours"),
                    ("waiting_client", "En attente client"),
                    ("waiting_provider", "En attente prestataire"),
                    ("no_response", "Sans réponse"),
                    ("cancelled", "Annulé"),
                    ("appointment_secured", "Rendez-vous sécurisé"),
                    ("done", "Rendez-vous honoré"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
