# Generated by Django 6.0.4 on 2026-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0024_providerbookingdraft_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketingservice",
            options={"ordering": ("homepage_order", "name")},
        ),
        migrations.AddField(
            model_name="marketingservice",
            name="homepage_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketingservice",
            name="is_visible_on_homepage",
            field=models.BooleanField(default=True),
        ),
    ]
