# Generated by Django 6.0.4 on 2026-04-25 18:56

import django.db.models.deletion
import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0034_providerbeforeappointmentitem"),
        ("interface", "0025_alter_marketingservice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingSubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("intro", models.TextField(blank=True)),
                ("short_intro", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketing/sub_services/main/"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                        max_length=500,
                        validators=[
                            interface.validators.validate_absolute_or_root_relative_url
                        ],
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "providers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="marketing_sub_services",
                        to="booking.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_services",
                        to="interface.marketingservice",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "slug"),
                        name="unique_marketing_sub_service_slug_per_service",
                    )
                ],
            },
        ),
    ]
