# Generated by Django 6.0.6 on 2026-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0026_marketingsubservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_at_home_bonus_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_base_price_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_booking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_general_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_hair_length_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_meche_bonus_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_price_label",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_service_fee_percentage",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
