# Generated by Django 6.0.6 on 2026-06-27 21:09

import django.db.models.deletion
import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0027_marketingsubservice_generic_at_home_bonus_cents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingSubServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="marketing/sub_services/gallery/"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                        max_length=500,
                        validators=[
                            interface.validators.validate_absolute_or_root_relative_url
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "sub_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="interface.marketingsubservice",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
