# Generated by Codex on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0040_reviewinvitation_verifiedreview"),
        ("interface", "0028_marketingsubserviceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerbookingdraft",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_drafts",
                to="booking.provider",
            ),
        ),
    ]
