# Generated by Django 6.1 on 2026-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0030_providerbookingdraft_follow_up_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingsubservice",
            name="generic_type_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
