# Generated by Django 6.1.1 on 2026-09-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0031_marketingsubservice_generic_type_adjustments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickcheckoutpage",
            name="location_preference",
            field=models.CharField(
                choices=[
                    ("domicile", "À domicile"),
                    ("salon", "Chez la prestataire ou le prestataire"),
                ],
                default="domicile",
                max_length=32,
            ),
        ),
    ]
