# Generated by Django 6.0 on 2025-12-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("contact_phone", models.CharField(blank=True, max_length=64)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_price_cents", models.IntegerField()),
                ("hair_length_adjustments", models.JSONField(blank=True, default=dict)),
                ("meche_adjustments", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="booking.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=64, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                ("client_phone", models.CharField(max_length=64)),
                ("location", models.CharField(max_length=255)),
                ("desired_date", models.CharField(max_length=128)),
                ("hair_length", models.CharField(max_length=64)),
                ("meche", models.CharField(max_length=64)),
                ("current_hair_picture", models.CharField(max_length=255)),
                ("inspiration_pictures", models.JSONField(default=list)),
                ("free_text", models.TextField(blank=True)),
                ("estimated_price_cents", models.IntegerField()),
                ("payment_auth_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "SUBMITTED"),
                            ("PENDING_CLIENT_VALIDATION", "PENDING_CLIENT_VALIDATION"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=64,
                    ),
                ),
                ("proposed_price_cents", models.IntegerField(blank=True, null=True)),
                (
                    "proposed_date",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_zones",
                        to="booking.provider",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_providers",
                        to="booking.zone",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "zone")},
            },
        ),
    ]
