# Generated by Django 6.0 on 2025-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("provider", "name")},
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="zone",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("provider", "name"), ("provider", "slug")},
        ),
    ]
