# Generated by Django 6.0 on 2025-12-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_force_add_meche_bonus_cents"),
        ("interface", "0003_alter_marketingcity_main_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="providers",
                through="booking.ProviderZone",
                to="booking.zone",
            ),
        ),
        migrations.CreateModel(
            name="ProviderMarketingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_marketing_services",
                        to="booking.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_service_providers",
                        to="interface.marketingservice",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "service")},
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="marketing_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="providers",
                through="booking.ProviderMarketingService",
                to="interface.marketingservice",
            ),
        ),
    ]
