# Generated by ChatGPT on 2025-02-03

from django.db import migrations


def sync_marketing_locations_to_zones(apps, schema_editor):
    Zone = apps.get_model("booking", "Zone")
    MarketingCity = apps.get_model("interface", "MarketingCity")
    MarketingDistrict = apps.get_model("interface", "MarketingDistrict")

    for city in MarketingCity.objects.all():
        Zone.objects.get_or_create(slug=city.slug, defaults={"name": city.name})

    for district in MarketingDistrict.objects.all():
        Zone.objects.get_or_create(slug=district.slug, defaults={"name": district.name})


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_backfill_provider_marketing_links"),
        ("interface", "0003_alter_marketingcity_main_image_url_and_more"),
    ]

    operations = [migrations.RunPython(sync_marketing_locations_to_zones, migrations.RunPython.noop)]

