# Generated by Django 6.0 on 2025-12-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_sync_marketing_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="works_in_salon_only",
            field=models.BooleanField(default=False),
        ),
    ]
