# Generated by Django 6.0 on 2025-12-29 15:29

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_provider_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="profile_image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AddField(
            model_name="providerphoto",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Upload an image or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
        migrations.AlterField(
            model_name="providerphoto",
            name="image",
            field=models.ImageField(blank=True, upload_to="providers/gallery/"),
        ),
    ]
