# Generated by Django 6.0 on 2026-01-06 17:16
from django.db import migrations, models


def forwards(apps, schema_editor):
    Provider = apps.get_model("booking", "Provider")

    for provider in Provider.objects.all():
        location_mode = "client_home_only"
        if getattr(provider, "works_in_salon_only", False):
            location_mode = "salon_only"
        provider.location_mode = location_mode
        provider.save(update_fields=["location_mode"])


def backwards(apps, schema_editor):
    Provider = apps.get_model("booking", "Provider")

    for provider in Provider.objects.all():
        provider.works_in_salon_only = (
            provider.location_mode == "salon_only"
        )
        provider.save(update_fields=["works_in_salon_only"])


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_provider_profile_image_url_providerphoto_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="location_mode",
            field=models.CharField(
                choices=[
                    ("salon_only", "Salon uniquement"),
                    ("client_home_only", "À domicile uniquement"),
                    ("hybrid", "Salon ou domicile"),
                ],
                default="hybrid",
                max_length=32,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="provider",
            name="works_in_salon_only",
        ),
    ]
