# Generated by Django 6.0.1 on 2026-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_rename_booking_client_phone_to_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="location_preference",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="provider",
            name="salon_address",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète du salon (communiquée après confirmation).",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="salon_zone",
            field=models.CharField(
                blank=True,
                help_text="Indique la zone ou le quartier où tu reçois au salon.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_email",
            field=models.EmailField(max_length=254),
        ),
    ]
