# Generated by Django 6.0.1 on 2026-01-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_service_general_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="Règles, conditions, informations complémentaires.",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="availabilities",
            field=models.TextField(
                blank=True, help_text="Disponibilités proposées pour la clientèle."
            ),
        ),
    ]
