# Generated by Django 6.0.1 on 2026-01-28 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0020_provider_additional_info_provider_availabilities"),
        ("booking", "0020_provider_provides_meche"),
    ]

    operations = []
