# Generated by Django 6.0.1 on 2026-01-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_booking_general_adjustment"),
        (
            "booking",
            "0021_merge_0020_provider_additional_info_provider_availabilities_0020_provider_provides_meche",
        ),
    ]

    operations = []
