# Generated by Django 6.0.1 on 2026-01-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_merge_20260128_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="categorized_services_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Active la présentation des services par catégories sur la page prestataire.",
            ),
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="booking.provider",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="booking.servicecategory",
            ),
        ),
    ]
