# Generated by Django 6.0.2 on 2026-02-14 16:30

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_provider_categorized_services_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="deposit_cents",
        ),
        migrations.AddField(
            model_name="provider",
            name="deposit_percentage",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Pourcentage de l'acompte appliqué sur l'estimation (ex: 30 pour 30%).",
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
    ]
