# Generated by Django 6.0.2 on 2026-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_provider_categorized_services_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="at_home_bonus_cents",
            field=models.IntegerField(default=0),
        ),
    ]
