# Generated by Django 6.0.2 on 2026-02-14 16:25

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_provider_categorized_services_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerphoto",
            name="media_kind",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="providerphoto",
            name="video",
            field=models.FileField(blank=True, upload_to="providers/gallery/videos/"),
        ),
        migrations.AddField(
            model_name="providerphoto",
            name="video_url",
            field=models.CharField(
                blank=True,
                help_text="Upload a video or provide an absolute URL, /root-relative path, or relative static asset path.",
                max_length=500,
                validators=[
                    interface.validators.validate_absolute_or_root_relative_url
                ],
            ),
        ),
    ]
