# Generated by Django 6.0.2 on 2026-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0026_booking_general_adjustments_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="homepage_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d'affichage sur la page d'accueil (plus petit = affiché en premier).",
            ),
        ),
    ]
