# Generated by Django 6.0.3 on 2026-03-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0027_provider_homepage_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderBlockedSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Blocage manuel"),
                            ("external_booked", "Créneau déjà pris (agenda externe)"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_slots",
                        to="booking.provider",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
            },
        ),
    ]
