# Generated by Django 6.0.3 on 2026-03-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_providerblockedslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerblockedslot",
            name="ends_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerblockedslot",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Active pour bloquer un créneau récurrent (hebdomadaire).",
            ),
        ),
        migrations.AddField(
            model_name="providerblockedslot",
            name="recurrence_ends_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerblockedslot",
            name="recurrence_starts_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerblockedslot",
            name="starts_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerblockedslot",
            name="weekdays",
            field=models.CharField(
                blank=True,
                help_text="Jours récurrents (0=lundi … 6=dimanche), séparés par des virgules.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="providerblockedslot",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="providerblockedslot",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
