# Generated by Django 6.0.3 on 2026-03-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0029_providerblockedslot_ends_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="is_visible_on_website",
            field=models.BooleanField(
                default=True,
                help_text="Décoche pour masquer ce profil des listes publiques du site (accueil, pages service, listes de prestataires).",
            ),
        ),
    ]
