# Generated by Django 6.0.3 on 2026-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0031_service_image_and_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="Texte H1 affiché sur la page prestataire à la place du prénom si renseigné.",
                max_length=255,
            ),
        ),
    ]
