# Generated by Django 6.0.4 on 2026-04-21 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0032_provider_seo_h1"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="service_fee_percentage",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Pourcentage de frais de service ajouté au prix des prestations.",
            ),
        ),
        migrations.CreateModel(
            name="ProviderServiceFeeCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_fee_coupons",
                        to="booking.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "code")},
            },
        ),
    ]
