# Generated by Django 6.0.4 on 2026-04-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0033_provider_service_fee_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderBeforeAppointmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="before_appointment_items",
                        to="booking.provider",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
