# Generated by Django 6.0.4 on 2026-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0034_providerbeforeappointmentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="locked_reservation_fee_cents",
            field=models.IntegerField(
                blank=True,
                help_text="Montant total effectivement payé/autorisé en acompte (modifiable pour préserver l'historique).",
                null=True,
            ),
        ),
    ]
