# Generated by Django 6.0.6 on 2026-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0035_booking_locked_reservation_fee_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="alternative_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING_CLIENT_VALIDATION", "PENDING_CLIENT_VALIDATION"),
                    ("AWAITING_ALTERNATIVE_PROVIDER", "AWAITING_ALTERNATIVE_PROVIDER"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                max_length=64,
            ),
        ),
    ]
