# Generated by Django 6.0.6 on 2026-06-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0036_booking_alternative_requested_at_and_more"),
        ("interface", "0026_marketingsubservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amount_due_now_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_kind",
            field=models.CharField(
                choices=[
                    ("PROVIDER_SELECTED", "Provider selected"),
                    ("GENERIC", "Generic request"),
                ],
                default="PROVIDER_SELECTED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="chateau_rose_fee_cents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="client_phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("REQUIRES_PAYMENT", "Requires payment"),
                    ("AUTHORIZED", "Authorized"),
                    ("WAIVED", "Waived"),
                    ("CAPTURED", "Captured"),
                    ("RELEASED", "Released"),
                ],
                default="REQUIRES_PAYMENT",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider_price_estimate_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="requested_marketing_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_intents",
                to="interface.marketingservice",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="requested_marketing_sub_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_intents",
                to="interface.marketingsubservice",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="requested_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booking",
            name="requested_service_label_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="service",
            name="marketing_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_services",
                to="interface.marketingservice",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="marketing_sub_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="provider_services",
                to="interface.marketingsubservice",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="current_hair_picture",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_auth_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="booking",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.provider",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.service",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING_CLIENT_VALIDATION", "PENDING_CLIENT_VALIDATION"),
                    ("AWAITING_ALTERNATIVE_PROVIDER", "AWAITING_ALTERNATIVE_PROVIDER"),
                    ("WAITING_PROVIDER_ASSIGNMENT", "WAITING_PROVIDER_ASSIGNMENT"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                max_length=64,
            ),
        ),
    ]
