# Generated by Django 6.0.6 on 2026-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0038_backfill_booking_platform_fee_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="inspiration_pictures",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
