# Generated by Django 6.0.7 on 2026-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0040_reviewinvitation_verifiedreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedreview",
            name="is_verified",
            field=models.BooleanField(
                default=True,
                help_text="Décochez pour les avis republiés depuis une source externe autorisée.",
            ),
        ),
    ]
