# Generated by Django 6.0.7 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0041_verified_review_trust_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedreview",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
