# Generated by Django 6.0.7 on 2026-08-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0042_verified_review_optional_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiedreview",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verified_review",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="verifiedreview",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="verifiedreview",
            name="client_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="verifiedreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_verified", False),
                    models.Q(
                        ("booking__isnull", False),
                        models.Q(("client_name", ""), _negated=True),
                        models.Q(("client_email", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="verified_review_requires_booking_and_client",
            ),
        ),
    ]
