# Generated by Django 6.1 on 2026-08-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0044_provider_contact_preferences_booking_state_entered_at"),
        ("interface", "0030_providerbookingdraft_follow_up_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="initial_provider_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="process_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING_CLIENT_VALIDATION", "PENDING_CLIENT_VALIDATION"),
                    ("AWAITING_ALTERNATIVE_PROVIDER", "AWAITING_ALTERNATIVE_PROVIDER"),
                    ("WAITING_PROVIDER_ASSIGNMENT", "WAITING_PROVIDER_ASSIGNMENT"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                    ("BOUNTY_OPEN", "BOUNTY_OPEN"),
                    ("BOUNTY_CLIENT_VALIDATION", "BOUNTY_CLIENT_VALIDATION"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="BookingOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("GENERIC", "Demande générique"),
                            ("PROVIDER_TIMEOUT", "Délai prestataire expiré"),
                            ("PROVIDER_REJECTED", "Refus prestataire"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("OFFERED", "OFFERED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("response_deadline_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="booking.booking",
                    ),
                ),
                (
                    "excluded_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excluded_booking_opportunities",
                        to="booking.provider",
                    ),
                ),
                (
                    "requested_sub_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_opportunities",
                        to="interface.marketingsubservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_date", models.CharField(max_length=128)),
                ("proposed_price_cents", models.PositiveIntegerField()),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CLIENT", "PENDING_CLIENT"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING_CLIENT",
                        max_length=24,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("client_deadline_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_offers",
                        to="booking.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_offers",
                        to="booking.service",
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="booking.bookingopportunity",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookingopportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("booking",),
                name="one_open_opportunity_per_booking",
            ),
        ),
    ]
