# Generated by Django 6.1 on 2026-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0045_booking_initial_provider_deadline_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="type_adjustment",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="service",
            name="type_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
