# Generated by Django 6.1.1 on 2026-09-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0048_alter_bookingoffer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="location_mode",
            field=models.CharField(
                choices=[
                    ("salon_only", "Chez la coiffeuse uniquement"),
                    ("client_home_only", "À domicile uniquement"),
                    ("hybrid", "Chez la coiffeuse ou à domicile"),
                ],
                default="hybrid",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="salon_address",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète du lieu de rendez-vous (communiquée après confirmation).",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="salon_zone",
            field=models.CharField(
                blank=True,
                help_text="Indique la zone ou le quartier où tu reçois ta clientèle.",
                max_length=255,
            ),
        ),
    ]
