# Generated by Django 6.1.1 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0049_alter_provider_location_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingopportunity",
            name="reason",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Demande générique"),
                    ("PROVIDER_TIMEOUT", "Délai prestataire expiré"),
                    ("PROVIDER_REJECTED", "Refus prestataire"),
                    (
                        "CLIENT_REJECTED_OFFER",
                        "Contre-proposition refusée par la cliente",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
